/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Akshat (https://sketchfab.com/shooter24994)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/moon-4db2273f6dd943b8ad7fa5e3b1b2431a
title: Moon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Moon.glb');
  const myMesh = React.useRef()
  useFrame(() => {
    myMesh.current.rotation.y += 0.003;
  })
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 2, 0]}>
        <group rotation={[Math.PI / 2, 2, 0]}>
          <group rotation={[-Math.PI / 2, 2, 0]} scale={3}>
            <mesh ref={myMesh} geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Moon.glb')
